language: java
jdk:
- oraclejdk8

stages:
  - name: test
    script:
      - ./gradlew test
  - name: deploy
    if: branch =~ ^draft OR tag =~ ^v
    script:
      - openssl aes-256-cbc -K $encrypted_f27c25e9ddd8_key -iv $encrypted_f27c25e9ddd8_iv -in oss_secring.gpg.enc -out oss_secring.gpg -d
      - ./gradlew uploadArchives