language: java
jdk:
- oraclejdk8

stages:
  - test
  - name: decrypt
    if: branch =~ ^draft OR tag =~ ^v
  - name: deploy
    if: branch =~ ^draft OR tag =~ ^v

jobs:
  include:
    - stage: test -X signArchives
      script: ./gradlew test -x signArchives
    - stage: decrypt
      script: openssl aes-256-cbc -K $encrypted_f27c25e9ddd8_key -iv $encrypted_f27c25e9ddd8_iv -in oss_secring.gpg.enc -out oss_secring.gpg -d
    - stage: deploy
      script: ./gradlew uploadArchives